#!/bin/sh
# EECS 2031 - Lab 8
# Filename: phone2
# Author: Thillanayagam, Lindan
# Email: lindan4@my.yorku.ca
# Login ID: lindan4

if test "$1" = ""
then
  echo "Usage: phone2 [wordToSearchFor]"
else
  grep -i "$1" "phone_book.txt"
fi
  